add debugging step

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -62,5 +62,13 @@ jobs:
         run: |
           EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
           echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
-          ls -al $RUNNER_TEMP
+
+          ARCHIVE_PATH=$RUNNER_TEMP/ritmix.xcarchive
+          if [ ! -d "$ARCHIVE_PATH" ]; then
+            echo "Error: Archive not found at $ARCHIVE_PATH"
+            exit 1
+          fi
+          
+          ls -R "$ARCHIVE_PATH"
+
           xcodebuild -exportArchive -archivePath $RUNNER_TEMP/ritmix.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build          
