update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -101,8 +101,12 @@ jobs:
           # Prepare the API key file from secret
           mkdir -p "$HOME/.appstoreconnect/private_keys"
           echo "${{ secrets.APP_STORE_API_PRIVATE_KEY }}" > ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APP_STORE_API_KEY_ID }}.p8
-          chmod 400 "~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APP_STORE_API_KEY_ID }}.p8"
-          ls -al ~/.appstoreconnect/private_keys
+
+          if [ ! -f "$HOME/.appstoreconnect/private_keys/AuthKey_***.p8" ]; then
+            echo "Error: API key file not found!"
+            exit 1
+          fi
+          chmod 400 $HOME/.appstoreconnect/private_keys/AuthKey_${{ secrets.APP_STORE_API_KEY_ID }}.p8
           
           # Upload to TestFlight using altool
           xcrun altool --upload-app \
